config/routes.rb
YougoboyApp::Application.routes.draw do
  resources :games

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'

  resources :words
  resources :kids

  devise_for :users

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :created_at, :kid_id, :points

  belongs_to :kid
end

app/models/kid.rb
class Kid < ActiveRecord::Base
  attr_accessible :charactor_img, :created_at, :family_id, :name, :updated_at

  belongs_to :family, class_name: "User"
  has_many :games, foreign_key: "kid_id"
  validates :name, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :familyname, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :kids, foreign_key: "family_id"
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :group, :level, :name

  GROUPS = %w(Fruits Vegetables Colors)
  LEVELS = 1..5

  validates :name, presence: true
  validates :group, presence: true, inclusion: { in: GROUPS }
  validates :level, presence: true, inclusion: { in: LEVELS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_filter :authenticate_user!

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kids }
    end
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
    @kid = Kid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kid }
    end
  end

  # GET /kids/new
  # GET /kids/new.json
  def new
    @kid = Kid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kid }
    end
  end

  # GET /kids/1/edit
  def edit
    @kid = Kid.find(params[:id])
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(params[:kid])
    @kid.family_id = current_user.id
    @kid.created_at = DateTime.now
    @kid.updated_at = DateTime.now

    respond_to do |format|
      if @kid.save
        format.html { redirect_to root_url, notice: 'Kid was successfully created.' }
        format.json { render json: @kid, status: :created, location: @kid }
      else
        format.html { render action: "new" }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kids/1
  # PUT /kids/1.json
  def update
    @kid = Kid.find(params[:id])

    respond_to do |format|
      if @kid.update_attributes(params[:kid])
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid = Kid.find(params[:id])
    @kid.destroy

    respond_to do |format|
      format.html { redirect_to kids_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/games/_form.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :kid_id %>
    <%= f.input :points %>
    <%= f.input :created_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Kid</th>
    <th>Points</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.kid_id %></td>
    <td><%= game.points %></td>
    <td><%= game.created_at %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Kid:</b>
  <%= @game.kid_id %>
</p>

<p>
  <b>Points:</b>
  <%= @game.points %>
</p>

<p>
  <b>Created at:</b>
  <%= @game.created_at %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/kids/_form.html.erb
<%= simple_form_for(@kid) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, wrapper: :prepend, label: false do %>
    <span class="add-on"><i class="icon-user"></i></span>
    <%= f.input_field :name, placeholder: "なまえ（ローマ字）", autofocus: true %>
  <% end %>
  <%= f.input :charactor_img, wrapper: :prepend, label: false do %>
    <span class="add-on"><i class="icon-camera"></i></span>
    <%= f.input_field :charactor_img, placeholder: "画像のURL" %>
  <% end %>

  <div class="form-actions">
    <%= button_tag type: 'submit', class: 'btn btn-large btn-success' do %>
      <i class="icon-ok"></i>&nbsp;Save
    <% end %>
  </div>
<% end %>

app/views/kids/edit.html.erb
<%= link_to @kid do %>
  <i class="icon-circle-arrow-left icon-4x pull-left left-btn"></i>
<% end %>
<h2>Edit Player</h2>
<hr>

<%= render 'form' %>

app/views/kids/index.html.erb
<h1>Listing kids</h1>

<table>
  <tr>
    <th>Family</th>
    <th>Name</th>
    <th>Charactor img</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kids.each do |kid| %>
  <tr>
    <td><%= kid.family_id %></td>
    <td><%= kid.name %></td>
    <td><%= kid.charactor_img %></td>
    <td><%= kid.created_at %></td>
    <td><%= kid.updated_at %></td>
    <td><%= link_to 'Show', kid %></td>
    <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
    <td><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kid', new_kid_path %>

app/views/kids/new.html.erb
<%= link_to root_path do %>
  <i class="icon-circle-arrow-left icon-4x pull-left left-btn"></i>
<% end %>
<h2>Add New Player</h2>
<hr>

<%= render 'form' %>

app/views/kids/show.html.erb
<%= link_to edit_kid_path do %>
  <i class="icon-pencil icon-4x pull-right right-btn"></i>
<% end %>
<%= link_to root_path do %>
  <i class="icon-circle-arrow-left icon-4x pull-left left-btn"></i>
<% end %>
<h2>Profile</h2>
<hr>
<% if notice %>
<div class="alert alert-info" id="notice"><%= notice %></div>
<% end %>
<div class="row">
  <div class="span4">
    <%= image_tag("#{@kid.charactor_img}", class: "img-circle") %>
  </div>
  <div>
    <table>
      <tbody>
        <tr>
          <td><strong>Family:</strong></td>
          <td><%= @kid.family.familyname %></td>
        </tr>
        <tr>
          <td><strong>Name:</strong></td>
          <td><%= @kid.name %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>You Go Boy!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= params[:controller].parameterize %>_controller">
  <div class="container-narrow">
    <div class="masthead">
      <ul class="nav nav-pills pull-right">
        <li>
        <a href="/"><i class="icon-home icon-2x"></i></a>
        </li>
        <li>
        <a href="/help"><i class="icon-question-sign icon-2x"></i></a>
        </li>
        <% if user_signed_in? %>
        <li>
          <%= link_to('<i class="icon-signout icon-2x"></i>'.html_safe, destroy_user_session_path, method: :delete) %>
        </li>
        <% else %>
        <li>
          <%= link_to('<i class="icon-signin icon-2x"></i>'.html_safe, new_user_session_path) %>
        </li>
        <li>
          <%= link_to('<i class="icon-plus-sign icon-2x"></i>'.html_safe, new_user_registration_path) %>
        </li>
        <% end %>
      </ul>
      <a href="/"><h3 class="muted">You Go Boy!</h3></a>
    </div>
    <hr>
    <div class="jumbotron">
      <div class="inside-jumbotron">
        <%= yield %>
      </div>
    </div>
    <hr>
    <div class="footer">
      <p>You Go Boy Project 2013</p>
    </div>
  </div><!-- /container-narrow -->
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/static_pages/help.html.erb
<h2>Help - ヘルプ</h2>
<hr>
<h4>You Go Boy! へようこそ！</h4>
<p>You Go Boy! は、<ruby><rb>英語</rb><rp>（</rp><rt>えいご</rt><rp>）</rp></ruby>をたのしく<ruby><rb>勉強</rb><rp>（</rp><rt>べんきょう</rt><rp>）</rp></ruby>するためのゲームです。</p>
<p>家族でひとつのアカウントをシェアするので、アカウントの作成がまだの家族は右上にある<i class="icon-plus-sign"></i>をクリックして作成してください。アカウントの作成が済んでいる（You Go Boy! に登録したメールアドレスとパスワードがわかる）場合は、右上の<i class="icon-signin"></i>からログインしてください。</p>
<p>ログインをしたら、家族に登録されているプレイヤーの一覧が表示されます。プレイヤーはいつでも追加できます。プレイヤーを選んで、ゲームを始めましょう。</p>
<p>プレイヤーを選んだら、ステージの選択画面が表示されます。ゲームのステージを選びましょう。ステージを選べば、ゲームスタートです！</p>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <div class="welcome">
    <h2>Welcome <%= current_user.familyname %>  Family</h2>
    <p class="lead">Choose a player! どの<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>であそぶ？</p>
    <div class="row row-player">
      <% current_user.kids.each do |kid| %>
      <div class="span-player">
        <%= image_tag("#{kid.charactor_img}", alt: "#{kid.name}", class: "img-circle player-img", data: { kid_id: kid.id }) %>
        <h4><%= kid.name %></h4>
      </div>
      <% end %>
      <div class="span-player">
        <%= link_to new_kid_path do %>
          <%= image_tag("add_player.png", class: "img-circle") %>
        <% end %>
        <h4>Add new player</h4>
      </div>
    </div>
  </div>
  <div class="game" style="display: none;">
  </div>
  <div id="gameModal" class="modal hide">
    <div class="modal-body">
      <img id="gameModalImg" class="img-rounded">
    </div>
  </div>
<% else %>
  <h1>You Go Boy!</h1>
  <p class="lead">Let's play together! おうちの<ruby><rb>人</rb><rp>（</rp><rt>ひと</rt><rp>）</rp></ruby>にログインしてもらってね</p>
  <%= link_to('<i class="icon-signin"></i> ログイン'.html_safe, new_user_session_path, class: "btn btn-large btn-success") %>
<% end %>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.select :level, Word::LEVELS %>
  </div>
  <div class="field">
    <%= f.label :group %><br />
    <%= f.select :group, Word::GROUPS %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h1>Listing words</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Level</th>
    <th>Group</th>
    <th>Image</th>
    <th>Sound</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @words.each do |word| %>
  <tr>
    <td><%= word.name %></td>
    <td><%= word.level %></td>
    <td><%= word.group %></td>
    <td><%= image_tag("words/#{word.name.downcase}.png", alt: word.name, width: 50, height: 50) %></td>
    <td><audio src="http://tts-api.com/tts.mp3?q=<%= word.name %>" controls></audio></td>
    <td><%= link_to 'Show', word %></td>
    <td><%= link_to 'Edit', edit_word_path(word) %></td>
    <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @word.name %>
</p>

<p>
  <b>Level:</b>
  <%= @word.level %>
</p>

<p>
  <b>Group:</b>
  <%= @word.group %>
</p>


<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>